
function [U]=interpolate_your_neighbour(U)

[x y z] =size(U);

U_t = U;
sq = sqrt(2);
den = (1+sq);

% for i = x/2:x-1
%     for j = y/2:y-1
%         for k=z/2:z-1
% 
%             if (U(i,j,k) ==0) && (U(i,j,k+1)~=0 || U(i,j,k-1)~=0 || ...
%                U(i,j-1,k)~=0 || U(i,j+1,k)~=0 ||  U(i+1,j,k)~=0 || ...
%                U(i-1,j,k)~=0 || U(i+1,j+1,k)~=0 || U(i-1,j-1,k)~=0 || ...
%                U(i-1,j+1,k)~=0 || U(i+1,j-1,k)~=0 || U(i+1,j,k-1)~=0 || ...
%                U(i+1,j,k+1)~=0 || U(i-1,j,k-1)~=0 || U(i+1,j,k+1)~=0 || ...
%                U(i,j-1,k-1)~=0 || U(i,j+1,k-1)~=0 || U(i,j-1,k+1)~=0 ||...
%                U(i,j+1,k+1)  )
%                
%                na = nnz( [U(i,j,k+1), U(i,j,k-1),U(i,j-1,k), U(i,j+1,k),...
%                    U(i+1,j,k),U(i-1,j,k)]);
%            
%                nb =nnz([ U(i+1,j+1,k), U(i-1,j-1,k), U(i,j+1,k-1)...
%                U(i-1,j+1,k), U(i+1,j-1,k), U(i+1,j,k-1), ...
%                U(i+1,j,k+1), U(i-1,j,k-1), U(i+1,j,k+1), ...
%                U(i,j-1,k-1), U(i,j+1,k+1), U(i,j-1,k+1)]);
%            
%            
%                   if(na~=0 && nb == 0)
%            
%                     U_t(i,j,k) = (U(i,j,k+1) + U(i,j,k-1) + ...
%                     U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
%                     U(i-1,j,k))/na;
%              
%                   end
%            
%                   if(na==0 && nb~=0)
%            
%                     U_t(i,j,k) = ( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
%                     U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
%                     U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
%                     U(i,j-1,k-1) + U(i,j+1,k+1) + U(i,j-1,k+1) + ...
%                     U(i,j+1,k-1))/nb; 
%            
%                   end
%                   
%                   if(na~= 0 && nb ~= 0)
%            
%                     U_t(i,j,k) = sq*((U(i,j,k+1) + U(i,j,k-1) + ...
%                     U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
%                     U(i-1,j,k))/na)/den + (( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
%                     U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
%                     U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
%                     U(i,j-1,k-1) + U(i,j+1,k-1) + U(i,j-1,k+1)+ U(i,j+1,k+1)...
%                     )/nb)/den;
%              
%                   end
%                   
%                 
%             end
%         end
%     end
% end
% 
% %1
% for i = x/2:-1:2
%     for j = y/2:y-1
%         for k=z/2:z-1
% 
%             if (U(i,j,k) ==0) && (U(i,j,k+1)~=0 || U(i,j,k-1)~=0 || ...
%                U(i,j-1,k)~=0 || U(i,j+1,k)~=0 ||  U(i+1,j,k)~=0 || ...
%                U(i-1,j,k)~=0 || U(i+1,j+1,k)~=0 || U(i-1,j-1,k)~=0 || ...
%                U(i-1,j+1,k)~=0 || U(i+1,j-1,k)~=0 || U(i+1,j,k-1)~=0 || ...
%                U(i+1,j,k+1)~=0 || U(i-1,j,k-1)~=0 || U(i+1,j,k+1)~=0 || ...
%                U(i,j-1,k-1)~=0 || U(i,j+1,k-1)~=0 || U(i,j-1,k+1)~=0 ||...
%                U(i,j+1,k+1)  )
%                
%                na = nnz( [U(i,j,k+1), U(i,j,k-1),U(i,j-1,k), U(i,j+1,k),...
%                    U(i+1,j,k),U(i-1,j,k)]);
%            
%                nb =nnz([ U(i+1,j+1,k), U(i-1,j-1,k), U(i,j+1,k-1)...
%                U(i-1,j+1,k), U(i+1,j-1,k), U(i+1,j,k-1), ...
%                U(i+1,j,k+1), U(i-1,j,k-1), U(i+1,j,k+1), ...
%                U(i,j-1,k-1), U(i,j+1,k+1), U(i,j-1,k+1)]);
%            
%            
%                   if(na~=0 && nb == 0)
%            
%                     U_t(i,j,k) = (U(i,j,k+1) + U(i,j,k-1) + ...
%                     U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
%                     U(i-1,j,k))/na;
%              
%                   end
%            
%                   if(na==0 && nb~=0)
%            
%                     U_t(i,j,k) = ( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
%                     U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
%                     U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
%                     U(i,j-1,k-1) + U(i,j+1,k+1) + U(i,j-1,k+1) + ...
%                     U(i,j+1,k-1))/nb; 
%            
%                   end
%                   
%                   if(na~= 0 && nb ~= 0)
%            
%                     U_t(i,j,k) = sq*((U(i,j,k+1) + U(i,j,k-1) + ...
%                     U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
%                     U(i-1,j,k))/na)/den + (( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
%                     U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
%                     U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
%                     U(i,j-1,k-1) + U(i,j+1,k-1) + U(i,j-1,k+1)+ U(i,j+1,k+1)...
%                     )/nb)/den;
%              
%                   end
%                   
%                 
%             end
%         end
%     end
% end
% 
% %2
% 
% for i = x/2:x-1
%     for j = y/2:-1:2
%         for k=z/2:z-1
% 
%             if (U(i,j,k) ==0) && (U(i,j,k+1)~=0 || U(i,j,k-1)~=0 || ...
%                U(i,j-1,k)~=0 || U(i,j+1,k)~=0 ||  U(i+1,j,k)~=0 || ...
%                U(i-1,j,k)~=0 || U(i+1,j+1,k)~=0 || U(i-1,j-1,k)~=0 || ...
%                U(i-1,j+1,k)~=0 || U(i+1,j-1,k)~=0 || U(i+1,j,k-1)~=0 || ...
%                U(i+1,j,k+1)~=0 || U(i-1,j,k-1)~=0 || U(i+1,j,k+1)~=0 || ...
%                U(i,j-1,k-1)~=0 || U(i,j+1,k-1)~=0 || U(i,j-1,k+1)~=0 ||...
%                U(i,j+1,k+1)  )
%                
%                na = nnz( [U(i,j,k+1), U(i,j,k-1),U(i,j-1,k), U(i,j+1,k),...
%                    U(i+1,j,k),U(i-1,j,k)]);
%            
%                nb =nnz([ U(i+1,j+1,k), U(i-1,j-1,k), U(i,j+1,k-1)...
%                U(i-1,j+1,k), U(i+1,j-1,k), U(i+1,j,k-1), ...
%                U(i+1,j,k+1), U(i-1,j,k-1), U(i+1,j,k+1), ...
%                U(i,j-1,k-1), U(i,j+1,k+1), U(i,j-1,k+1)]);
%            
%            
%                   if(na~=0 && nb == 0)
%            
%                     U_t(i,j,k) = (U(i,j,k+1) + U(i,j,k-1) + ...
%                     U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
%                     U(i-1,j,k))/na;
%              
%                   end
%            
%                   if(na==0 && nb~=0)
%            
%                     U_t(i,j,k) = ( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
%                     U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
%                     U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
%                     U(i,j-1,k-1) + U(i,j+1,k+1) + U(i,j-1,k+1) + ...
%                     U(i,j+1,k-1))/nb; 
%            
%                   end
%                   
%                   if(na~= 0 && nb ~= 0)
%            
%                     U_t(i,j,k) = sq*((U(i,j,k+1) + U(i,j,k-1) + ...
%                     U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
%                     U(i-1,j,k))/na)/den + (( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
%                     U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
%                     U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
%                     U(i,j-1,k-1) + U(i,j+1,k-1) + U(i,j-1,k+1)+ U(i,j+1,k+1)...
%                     )/nb)/den;
%              
%                   end
%                   
%                 
%             end
%         end
%     end
% end
% 
% %3
% 
% 
% 
% 
% for i = x/2:-1:2
%     for j = y/2:-1:2
%         for k=z/2:z-1
% 
%             if (U(i,j,k) ==0) && (U(i,j,k+1)~=0 || U(i,j,k-1)~=0 || ...
%                U(i,j-1,k)~=0 || U(i,j+1,k)~=0 ||  U(i+1,j,k)~=0 || ...
%                U(i-1,j,k)~=0 || U(i+1,j+1,k)~=0 || U(i-1,j-1,k)~=0 || ...
%                U(i-1,j+1,k)~=0 || U(i+1,j-1,k)~=0 || U(i+1,j,k-1)~=0 || ...
%                U(i+1,j,k+1)~=0 || U(i-1,j,k-1)~=0 || U(i+1,j,k+1)~=0 || ...
%                U(i,j-1,k-1)~=0 || U(i,j+1,k-1)~=0 || U(i,j-1,k+1)~=0 ||...
%                U(i,j+1,k+1)  )
%                
%                na = nnz( [U(i,j,k+1), U(i,j,k-1),U(i,j-1,k), U(i,j+1,k),...
%                    U(i+1,j,k),U(i-1,j,k)]);
%            
%                nb =nnz([ U(i+1,j+1,k), U(i-1,j-1,k), U(i,j+1,k-1)...
%                U(i-1,j+1,k), U(i+1,j-1,k), U(i+1,j,k-1), ...
%                U(i+1,j,k+1), U(i-1,j,k-1), U(i+1,j,k+1), ...
%                U(i,j-1,k-1), U(i,j+1,k+1), U(i,j-1,k+1)]);
%            
%            
%                   if(na~=0 && nb == 0)
%            
%                     U_t(i,j,k) = (U(i,j,k+1) + U(i,j,k-1) + ...
%                     U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
%                     U(i-1,j,k))/na;
%              
%                   end
%            
%                   if(na==0 && nb~=0)
%            
%                     U_t(i,j,k) = ( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
%                     U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
%                     U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
%                     U(i,j-1,k-1) + U(i,j+1,k+1) + U(i,j-1,k+1) + ...
%                     U(i,j+1,k-1))/nb; 
%            
%                   end
%                   
%                   if(na~= 0 && nb ~= 0)
%            
%                     U_t(i,j,k) = sq*((U(i,j,k+1) + U(i,j,k-1) + ...
%                     U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
%                     U(i-1,j,k))/na)/den + (( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
%                     U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
%                     U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
%                     U(i,j-1,k-1) + U(i,j+1,k-1) + U(i,j-1,k+1)+ U(i,j+1,k+1)...
%                     )/nb)/den;
%              
%                   end
%                   
%                 
%             end
%         end
%     end
% end
% 
% %4
% 
% 
% 
% % for i = x/2:x-1
% %     for j = y/2:y-1
% %         for k= z/2:-1:2
% % 
% %             if (U(i,j,k) ==0) && (U(i,j,k+1)~=0 || U(i,j,k-1)~=0 || ...
% %                U(i,j-1,k)~=0 || U(i,j+1,k)~=0 ||  U(i+1,j,k)~=0 || ...
% %                U(i-1,j,k)~=0 || U(i+1,j+1,k)~=0 || U(i-1,j-1,k)~=0 || ...
% %                U(i-1,j+1,k)~=0 || U(i+1,j-1,k)~=0 || U(i+1,j,k-1)~=0 || ...
% %                U(i+1,j,k+1)~=0 || U(i-1,j,k-1)~=0 || U(i+1,j,k+1)~=0 || ...
% %                U(i,j-1,k-1)~=0 || U(i,j+1,k-1)~=0 || U(i,j-1,k+1)~=0 ||...
% %                U(i,j+1,k+1)  )
% %                
% %                na = nnz( [U(i,j,k+1), U(i,j,k-1),U(i,j-1,k), U(i,j+1,k),...
% %                    U(i+1,j,k),U(i-1,j,k)]);
% %            
% %                nb =nnz([ U(i+1,j+1,k), U(i-1,j-1,k), U(i,j+1,k-1)...
% %                U(i-1,j+1,k), U(i+1,j-1,k), U(i+1,j,k-1), ...
% %                U(i+1,j,k+1), U(i-1,j,k-1), U(i+1,j,k+1), ...
% %                U(i,j-1,k-1), U(i,j+1,k+1), U(i,j-1,k+1)]);
% %            
% %            
% %                   if(na~=0 && nb == 0)
% %            
% %                     U_t(i,j,k) = (U(i,j,k+1) + U(i,j,k-1) + ...
% %                     U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
% %                     U(i-1,j,k))/na;
% %              
% %                   end
% %            
% %                   if(na==0 && nb~=0)
% %            
% %                     U_t(i,j,k) = ( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
% %                     U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
% %                     U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
% %                     U(i,j-1,k-1) + U(i,j+1,k+1) + U(i,j-1,k+1) + ...
% %                     U(i,j+1,k-1))/nb; 
% %            
% %                   end
% %                   
% %                   if(na~= 0 && nb ~= 0)
% %            
% %                     U_t(i,j,k) = sq*((U(i,j,k+1) + U(i,j,k-1) + ...
% %                     U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
% %                     U(i-1,j,k))/na)/den + (( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
% %                     U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
% %                     U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
% %                     U(i,j-1,k-1) + U(i,j+1,k-1) + U(i,j-1,k+1)+ U(i,j+1,k+1)...
% %                     )/nb)/den;
% %              
% %                   end
% %                   
% %                 
% %             end
% %         end
% %     end
% % end
% 
% %5
% for i = x/2:-1:2
%     for j = y/2:-1:2
%         for k = z/2:-1:2
% 
%             if (U(i,j,k) ==0) && (U(i,j,k+1)~=0 || U(i,j,k-1)~=0 || ...
%                U(i,j-1,k)~=0 || U(i,j+1,k)~=0 ||  U(i+1,j,k)~=0 || ...
%                U(i-1,j,k)~=0 || U(i+1,j+1,k)~=0 || U(i-1,j-1,k)~=0 || ...
%                U(i-1,j+1,k)~=0 || U(i+1,j-1,k)~=0 || U(i+1,j,k-1)~=0 || ...
%                U(i+1,j,k+1)~=0 || U(i-1,j,k-1)~=0 || U(i+1,j,k+1)~=0 || ...
%                U(i,j-1,k-1)~=0 || U(i,j+1,k-1)~=0 || U(i,j-1,k+1)~=0 ||...
%                U(i,j+1,k+1)  )
%                
%                na = nnz( [U(i,j,k+1), U(i,j,k-1),U(i,j-1,k), U(i,j+1,k),...
%                    U(i+1,j,k),U(i-1,j,k)]);
%            
%                nb =nnz([ U(i+1,j+1,k), U(i-1,j-1,k), U(i,j+1,k-1)...
%                U(i-1,j+1,k), U(i+1,j-1,k), U(i+1,j,k-1), ...
%                U(i+1,j,k+1), U(i-1,j,k-1), U(i+1,j,k+1), ...
%                U(i,j-1,k-1), U(i,j+1,k+1), U(i,j-1,k+1)]);
%            
%            
%                   if(na~=0 && nb == 0)
%            
%                     U_t(i,j,k) = (U(i,j,k+1) + U(i,j,k-1) + ...
%                     U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
%                     U(i-1,j,k))/na;
%              
%                   end
%            
%                   if(na==0 && nb~=0)
%            
%                     U_t(i,j,k) = ( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
%                     U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
%                     U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
%                     U(i,j-1,k-1) + U(i,j+1,k+1) + U(i,j-1,k+1) + ...
%                     U(i,j+1,k-1))/nb; 
%            
%                   end
%                   
%                   if(na~= 0 && nb ~= 0)
%            
%                     U_t(i,j,k) = sq*((U(i,j,k+1) + U(i,j,k-1) + ...
%                     U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
%                     U(i-1,j,k))/na)/den + (( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
%                     U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
%                     U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
%                     U(i,j-1,k-1) + U(i,j+1,k-1) + U(i,j-1,k+1)+ U(i,j+1,k+1)...
%                     )/nb)/den;
%              
%                   end
%                   
%                 
%             end
%         end
%     end
% end
% 
% 
% 
% %6
% 
% 
% 
% for i = 2:x/2
%     for j = y/2:-1:2
%         for k = z/2:-1:2
% 
%             if (U(i,j,k) ==0) && (U(i,j,k+1)~=0 || U(i,j,k-1)~=0 || ...
%                U(i,j-1,k)~=0 || U(i,j+1,k)~=0 ||  U(i+1,j,k)~=0 || ...
%                U(i-1,j,k)~=0 || U(i+1,j+1,k)~=0 || U(i-1,j-1,k)~=0 || ...
%                U(i-1,j+1,k)~=0 || U(i+1,j-1,k)~=0 || U(i+1,j,k-1)~=0 || ...
%                U(i+1,j,k+1)~=0 || U(i-1,j,k-1)~=0 || U(i+1,j,k+1)~=0 || ...
%                U(i,j-1,k-1)~=0 || U(i,j+1,k-1)~=0 || U(i,j-1,k+1)~=0 ||...
%                U(i,j+1,k+1)  )
%                
%                na = nnz( [U(i,j,k+1), U(i,j,k-1),U(i,j-1,k), U(i,j+1,k),...
%                    U(i+1,j,k),U(i-1,j,k)]);
%            
%                nb =nnz([ U(i+1,j+1,k), U(i-1,j-1,k), U(i,j+1,k-1)...
%                U(i-1,j+1,k), U(i+1,j-1,k), U(i+1,j,k-1), ...
%                U(i+1,j,k+1), U(i-1,j,k-1), U(i+1,j,k+1), ...
%                U(i,j-1,k-1), U(i,j+1,k+1), U(i,j-1,k+1)]);
%            
%            
%                   if(na~=0 && nb == 0)
%            
%                     U_t(i,j,k) = (U(i,j,k+1) + U(i,j,k-1) + ...
%                     U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
%                     U(i-1,j,k))/na;
%              
%                   end
%            
%                   if(na==0 && nb~=0)
%            
%                     U_t(i,j,k) = ( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
%                     U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
%                     U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
%                     U(i,j-1,k-1) + U(i,j+1,k+1) + U(i,j-1,k+1) + ...
%                     U(i,j+1,k-1))/nb; 
%            
%                   end
%                   
%                   if(na~= 0 && nb ~= 0)
%            
%                     U_t(i,j,k) = sq*((U(i,j,k+1) + U(i,j,k-1) + ...
%                     U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
%                     U(i-1,j,k))/na)/den + (( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
%                     U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
%                     U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
%                     U(i,j-1,k-1) + U(i,j+1,k-1) + U(i,j-1,k+1)+ U(i,j+1,k+1)...
%                     )/nb)/den;
%              
%                   end
%                   
%                 
%             end
%         end
%     end
% end
% 
% 
% 
% %7
% 
% for i = x/2:-1:2
%     for j = y/2:y-1
%         for k = z/2:-1:2
% 
%             if (U(i,j,k) ==0) && (U(i,j,k+1)~=0 || U(i,j,k-1)~=0 || ...
%                U(i,j-1,k)~=0 || U(i,j+1,k)~=0 ||  U(i+1,j,k)~=0 || ...
%                U(i-1,j,k)~=0 || U(i+1,j+1,k)~=0 || U(i-1,j-1,k)~=0 || ...
%                U(i-1,j+1,k)~=0 || U(i+1,j-1,k)~=0 || U(i+1,j,k-1)~=0 || ...
%                U(i+1,j,k+1)~=0 || U(i-1,j,k-1)~=0 || U(i+1,j,k+1)~=0 || ...
%                U(i,j-1,k-1)~=0 || U(i,j+1,k-1)~=0 || U(i,j-1,k+1)~=0 ||...
%                U(i,j+1,k+1)  )
%                
%                na = nnz( [U(i,j,k+1), U(i,j,k-1),U(i,j-1,k), U(i,j+1,k),...
%                    U(i+1,j,k),U(i-1,j,k)]);
%            
%                nb =nnz([ U(i+1,j+1,k), U(i-1,j-1,k), U(i,j+1,k-1)...
%                U(i-1,j+1,k), U(i+1,j-1,k), U(i+1,j,k-1), ...
%                U(i+1,j,k+1), U(i-1,j,k-1), U(i+1,j,k+1), ...
%                U(i,j-1,k-1), U(i,j+1,k+1), U(i,j-1,k+1)]);
%            
%            
%                   if(na~=0 && nb == 0)
%            
%                     U_t(i,j,k) = (U(i,j,k+1) + U(i,j,k-1) + ...
%                     U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
%                     U(i-1,j,k))/na;
%              
%                   end
%            
%                   if(na==0 && nb~=0)
%            
%                     U_t(i,j,k) = ( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
%                     U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
%                     U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
%                     U(i,j-1,k-1) + U(i,j+1,k+1) + U(i,j-1,k+1) + ...
%                     U(i,j+1,k-1))/nb; 
%            
%                   end
%                   
%                   if(na~= 0 && nb ~= 0)
%            
%                     U_t(i,j,k) = sq*((U(i,j,k+1) + U(i,j,k-1) + ...
%                     U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
%                     U(i-1,j,k))/na)/den + (( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
%                     U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
%                     U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
%                     U(i,j-1,k-1) + U(i,j+1,k-1) + U(i,j-1,k+1)+ U(i,j+1,k+1)...
%                     )/nb)/den;
%              
%                   end
%                   
%                 
%             end
%         end
%     end
% end
% 
% %8
% 
% 
% 
% 
% 
% for i = 2:x/2
%     for j = 2:y/2
%         for k = z/2:-1/2
% 
%             if (U(i,j,k) ==0) && (U(i,j,k+1)~=0 || U(i,j,k-1)~=0 || ...
%                U(i,j-1,k)~=0 || U(i,j+1,k)~=0 ||  U(i+1,j,k)~=0 || ...
%                U(i-1,j,k)~=0 || U(i+1,j+1,k)~=0 || U(i-1,j-1,k)~=0 || ...
%                U(i-1,j+1,k)~=0 || U(i+1,j-1,k)~=0 || U(i+1,j,k-1)~=0 || ...
%                U(i+1,j,k+1)~=0 || U(i-1,j,k-1)~=0 || U(i+1,j,k+1)~=0 || ...
%                U(i,j-1,k-1)~=0 || U(i,j+1,k-1)~=0 || U(i,j-1,k+1)~=0 ||...
%                U(i,j+1,k+1)  )
%                
%                na = nnz( [U(i,j,k+1), U(i,j,k-1),U(i,j-1,k), U(i,j+1,k),...
%                    U(i+1,j,k),U(i-1,j,k)]);
%            
%                nb =nnz([ U(i+1,j+1,k), U(i-1,j-1,k), U(i,j+1,k-1)...
%                U(i-1,j+1,k), U(i+1,j-1,k), U(i+1,j,k-1), ...
%                U(i+1,j,k+1), U(i-1,j,k-1), U(i+1,j,k+1), ...
%                U(i,j-1,k-1), U(i,j+1,k+1), U(i,j-1,k+1)]);
%            
%            
%                   if(na~=0 && nb == 0)
%            
%                     U_t(i,j,k) = (U(i,j,k+1) + U(i,j,k-1) + ...
%                     U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
%                     U(i-1,j,k))/na;
%              
%                   end
%            
%                   if(na==0 && nb~=0)
%            
%                     U_t(i,j,k) = ( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
%                     U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
%                     U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
%                     U(i,j-1,k-1) + U(i,j+1,k+1) + U(i,j-1,k+1) + ...
%                     U(i,j+1,k-1))/nb; 
%            
%                   end
%                   
%                   if(na~= 0 && nb ~= 0)
%            
%                     U_t(i,j,k) = sq*((U(i,j,k+1) + U(i,j,k-1) + ...
%                     U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
%                     U(i-1,j,k))/na)/den + (( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
%                     U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
%                     U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
%                     U(i,j-1,k-1) + U(i,j+1,k-1) + U(i,j-1,k+1)+ U(i,j+1,k+1)...
%                     )/nb)/den;
%              
%                   end
%                   
%                 
%             end
%         end
%     end
% end
% 
% 
% 









%=============================================




%



for i = 2:x-1
    for j = 2:y-1
        for k=2:z-1

            if (U(i,j,k) ==0) && (U(i,j,k+1)~=0 || U(i,j,k-1)~=0 || ...
               U(i,j-1,k)~=0 || U(i,j+1,k)~=0 ||  U(i+1,j,k)~=0 || ...
               U(i-1,j,k)~=0 || U(i+1,j+1,k)~=0 || U(i-1,j-1,k)~=0 || ...
               U(i-1,j+1,k)~=0 || U(i+1,j-1,k)~=0 || U(i+1,j,k-1)~=0 || ...
               U(i+1,j,k+1)~=0 || U(i-1,j,k-1)~=0 || U(i+1,j,k+1)~=0 || ...
               U(i,j-1,k-1)~=0 || U(i,j+1,k-1)~=0 || U(i,j-1,k+1)~=0 ||...
               U(i,j+1,k+1)  )

               na = nnz( [U(i,j,k+1), U(i,j,k-1),U(i,j-1,k), U(i,j+1,k),...
                   U(i+1,j,k),U(i-1,j,k)]);

               nb =nnz([ U(i+1,j+1,k), U(i-1,j-1,k), U(i,j+1,k-1)...
               U(i-1,j+1,k), U(i+1,j-1,k), U(i+1,j,k-1), ...
               U(i+1,j,k+1), U(i-1,j,k-1), U(i+1,j,k+1), ...
               U(i,j-1,k-1), U(i,j+1,k+1), U(i,j-1,k+1)]);


                  if(na~=0 && nb == 0)

                    U_t(i,j,k) = (U(i,j,k+1) + U(i,j,k-1) + ...
                    U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
                    U(i-1,j,k))/na;

                  end

                  if(na==0 && nb~=0)

                    U_t(i,j,k) = ( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
                    U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
                    U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
                    U(i,j-1,k-1) + U(i,j+1,k+1) + U(i,j-1,k+1) + ...
                    U(i,j+1,k-1))/nb;

                  end

                  if(na~= 0 && nb ~= 0)

                    U_t(i,j,k) = sq*((U(i,j,k+1) + U(i,j,k-1) + ...
                    U(i,j-1,k) + U(i,j+1,k) +  U(i+1,j,k) + ...
                    U(i-1,j,k))/na)/den + (( U(i+1,j+1,k) + U(i-1,j-1,k) + ...
                    U(i-1,j+1,k) + U(i+1,j-1,k) + U(i+1,j,k-1) + ...
                    U(i+1,j,k+1) + U(i-1,j,k-1) + U(i+1,j,k+1) + ...
                    U(i,j-1,k-1) + U(i,j+1,k-1) + U(i,j-1,k+1)+ U(i,j+1,k+1)...
                    )/nb)/den;

                  end


            end
        end
    end
end
























U = U_t;
             
               
               